"use client"

import './../globals.css'
import SearchIcon from '@mui/icons-material/Search';
import Nav from './navleft/nav'



// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function DashboardLayout({
  children, // will be a page or nested layout
}) {
  return (
    <section className='w-full flex flex-wrap '>
      {/* Include shared UI here e.g. a header or sidebar */}
      <div className='lg:w-[15%] w-full *:bg-[#376fd0]  text-white'>
        <h2 className='p-3 text-2xl w-full bg-[#2e5dad] text-center capitalize'>admin panel</h2>
        <p className='capitalize p-5 font-bold text-slate-300'>pages</p>

        <Nav/>
        {/* <ul className='flex flex-wrap justify-center gap-3 *:w-full'>
          <li><Link className='flex items-center w-full justify-center py-2 capitalize hover:bg-black' href={'/dashboard/soon'}><IoDocumentOutline /><span className='px-2'>documentation</span></Link></li>

        </ul> */}
      </div>
      <header className='lg:w-[85%] w-full absolute right-0  flex items-center *:mx-5 text-slate-400 h-14 bg-white'>
        <i><SearchIcon/></i>
        <input type="text" placeholder='search products' className='bg-transparent w-2/3 p-2 border text-slate-500' />
    
      </header>
      <div className='w-[85%]  mt-14'>
        {children}
      </div>
    </section>
  )
}